# Generated by Django 4.0.4 on 2022-05-02 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_companies_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='location',
            new_name='locations',
        ),
    ]
