# Generated by Django 4.0.4 on 2022-05-02 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_location_active'),
        ('app2', '0003_rename_location_companies_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='locations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.location'),
        ),
    ]
